### ISSUE TITLE
Some problems with using proxy and captcha.

### ISSUE THREAD

**Issue by sap2me** [bukson/steampy#146] opened 2019-05-13 15:44 UTC
Hi, i have some problems with using proxy.
I am trying to run my bot on VDS, but steam understands it and asks for captcha.

![image](https://user-images.githubusercontent.com/47041160/57634465-062ecb00-75ae-11e9-8ece-0b87ae27b647.png)

That is why i am using proxy:

```
self.client = SteamClient(self.API)
self.client._session.proxies.update({'https': 'https://sp****:S7l4TlE@193.169.86.59:65233'})
```

So everything works, send an offer and so on. But after 2 minutes after authorization, the offer stops sending and gives this error. It is worth canceling that without a proxy this error does not exist, and everything works.

![image](https://user-images.githubusercontent.com/47041160/57634769-a684ef80-75ae-11e9-90b7-45b0d152d0c1.png)

Could you tell me what's the matter, how to properly use a proxy, and how to solve this problem with the captcha without a proxy. Thanks.

**Comment by astroaut** [comment] 2019-05-28 15:31
If you use multiple bot accounts you need to wait 30 secs before login again.
Or if you login to 1 account you can solve captcha by yourself or use to captcha solving service.

**Comment by sap2me** [comment] 2019-05-28 15:58
> If you use multiple bot accounts you need to wait 30 secs before login again.
> Or if you login to 1 account you can solve captcha by yourself or use to captcha solving service.
> 
> Problem with proxy mean that proxy working not properly. You can buy private proxy and don't experience such problem.

Thank you for the answer, but how to solve captcha by myself using steampy? Could you show code example please.

**Comment by astroaut** [comment] 2019-06-01 07:21
> Thank you for the answer, but how to solve captcha by myself using steampy? Could you show code example please.

Sorry, i can't reproduce this error on my machine. I can help you only if i have access to your machine. Write me in telegram: astroaut

**Comment by Apollon76** [comment] 2019-06-22 20:00
I had the same issue. I simply logged in using vds as a proxy from my browser and entered the captcha manually.

**Comment by bukson** [comment] 2019-08-04 21:56
Hello, the steampy was designed to be fully automated, there are some services with api for captcha resolving, I think the proper answer would be for example to write method than solves captchas and catching the captcha presense exception.

**Closed** 2020-11-01 14:38 UTC
