### ISSUE TITLE
Login doesn't work after the steam chat update

### ISSUE THREAD

**Issue by Cagrimanoka** [bukson/steampy#126] opened 2018-06-12 20:34 UTC
Since chat got updated by steam, it gives an error on chat._login while trying to login with .login . Here is the error:

```
Traceback (most recent call last):
  File "C:/Users/cagri/Desktop/py/trade.py", line 65, in <module>
    steam_client.login(steamusername, steampassword, "Steamguard.txt")
  File "C:\Users\cagri\Desktop\py\venv\lib\site-packages\steampy\client.py", line 44, in login
    self.chat._login()
  File "C:\Users\cagri\Desktop\py\venv\lib\site-packages\steampy\chat.py", line 38, in _login
    self._chat_params["access_token"] = self._get_access_token()
  File "C:\Users\cagri\Desktop\py\venv\lib\site-packages\steampy\chat.py", line 19, in _get_access_token
    access_token = token_pattern.search(str(elems[0])).group(1)
IndexError: list index out of range

**Comment by bukson** [comment] 2018-06-13 08:52
Ok i will look into that

**Comment by amdev0** [comment] 2018-06-19 08:10
I can confirm this too, any updates?

**Comment by Blurrez** [comment] 2018-06-20 22:03
and http://prntscr.com/jxcxwd

**Comment by amdev0** [comment] 2018-06-21 01:35
The cause of this issue is steam chat got updated and steampy relies on extracting an access token from html, which is then used to interact with the chat via Steam's Web API. I tried changing it so it correctly extracts the token. However those Web API methods are undocumented and they may have stopped working. It's also possible I just did something wrong. Either way, I think doing it the way other steam libraries do it would be a better solution, not relying on the Web API for chat.

**Comment by Phalelashvili** [comment] 2018-07-07 20:49
any updates?

**Comment by Blurrez** [comment] 2018-07-07 20:51
no :(

**Comment by Phalelashvili** [comment] 2018-07-07 20:54
i think i found way to fix, it's finding token in html with soup, i just have to modify pattern which it searchs for

**Comment by Phalelashvili** [comment] 2018-07-08 08:30
i fixed this one but there's more, steam update screwed everything up

**Comment by Phalelashvili** [comment] 2018-07-08 08:46
here's modified chat.py that can get token but now i'm getting requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.steampowered.com/ISteamWebUserPresenceOAuth/Logon/v1


```
import bs4
import re
from steampy.models import Endpoints, SteamUrl
from steampy.utils import account_id_to_steam_id


class SteamChat():

    def __init__(self, session):
        self._session = session
        self._chat_params = {}

    #modified
    def _get_access_token(self):
        response = self._session.get(SteamUrl.COMMUNITY_URL + "/chat")
        response.raise_for_status()
        response_soup = bs4.BeautifulSoup(response.text, "html.parser")
        userinfo = response_soup.find("div", {"id":"webui_config"})['data-userinfo']
        userinfo = userinfo.replace('true', '"dict had boolean true in it (javascript), python couldn\'t recognize it so i had to change xD"')
        userinfo = eval(userinfo)
        access_token = userinfo['token']
        print(access_token)
        if access_token is None:
            raise Exception("Failed to retrieve the access_token")
        else:
            return access_token

    def _api_call(self, endpoint, params, timeout_ignore=False):
        response = self._session.post(endpoint, data=params)
        response.raise_for_status()
        response_status = response.json().get("error")
        if timeout_ignore and response_status == "Timeout":
            return
        elif response_status != "OK":
            raise Exception(response_status)
        else:
            return response

    def _login(self, ui_mode="web"):
        self._chat_params["ui_mode"] = ui_mode
        self._chat_params["access_token"] = self._get_access_token()
        endpoint = Endpoints.CHAT_LOGIN
        params = {"ui_mode": self._chat_params.get("ui_mode"),
                  "access_token": self._chat_params.get("access_token")}
        response = self._api_call(endpoint, params)
        self._chat_params.update(response.json())
        return response

    def _logout(self):
        endpoint = Endpoints.CHAT_LOGOUT
        params = {"access_token": self._chat_params.get("access_token"),
                  "umqid": self._chat_params.get("umqid")}
        self._chat_params = {}
        return self._api_call(endpoint, params)

    def send_message(self, steamid_64, text):
        endpoint = Endpoints.SEND_MESSAGE
        params = {"access_token": self._chat_params.get("access_token"),
                  "steamid_dst": steamid_64,
                  "text": text,
                  "type": "saytext",
                  "umqid": self._chat_params.get("umqid")}
        return self._api_call(endpoint, params)

    def poll_events(self) -> dict:
        endpoint = Endpoints.CHAT_POLL
        params = {"access_token": self._chat_params.get("access_token"),
                  "umqid": self._chat_params.get("umqid"),
                  "message": self._chat_params.get("message"),
                  "pollid": 1,
                  "sectimeout": 20,
                  "secidletime": 0,
                  "use_accountids": 1}
        response = self._api_call(endpoint, params, timeout_ignore=True)
        if not response:
            return {}
        data = response.json()
        self._chat_params["message"] = data["messagelast"]
        return response.json()

    def fetch_messages(self) -> dict:
        message_list = {
            'sent': [],
            'received': []
        }
        events = self.poll_events()
        if not events:
            return message_list
        messages = events["messages"]
        for message in messages:
            text = message.get("text")
            if message['type'] == "saytext":
                accountid_from = account_id_to_steam_id(message.get("accountid_from"))
                message_list['received'].append({"partner": accountid_from, "message": text})
            elif message['type'] == "my_saytext":
                accountid_from = account_id_to_steam_id(message.get("accountid_from"))
                message_list['sent'].append({"partner": accountid_from, "message": text})
        return message_list

```

**Comment by bukson** [comment] 2018-07-11 10:55
Ok guys, sorry i was on vacations and then sick. I updated steampy to 0.52 version where I disable automatic login to chat, so it is quick fix, now i will try to fix real issue

**Comment by bukson** [comment] 2018-07-12 20:46
Ok i am opening isssue #128  and closing this one

**Closed by bukson** 2018-07-12 20:46 UTC
